import monstera from "../image/monstera.jpeg";

export const plantList = [
  {
    name: "monstera",
    category: "classique",
    id: "1ed",
    water: 1,
    light: 1,
    isBestSale: true,
    cover: monstera,
    price: 15,
  },
  {
    name: "ficus lyrata",
    category: "classique",
    id: "2ab",
    water: 1,
    light: 1,
    cover: monstera,
    price: 15,
  },
  {
    name: "pothos argenté",
    category: "classique",
    id: "3sd",
    water: 1,
    light: 1,
    isSpecialOffer: true,
    cover: monstera,
    price: 15,
  },
  {
    name: "yucca",
    category: "classique",
    id: "4kk",
    water: 1,
    light: 1,
    cover: monstera,
    price: 15,
  },
  {
    name: "olivier",
    category: "extérieur",
    id: "5pl",
    water: 1,
    light: 1,
    cover: monstera,
    price: 15,
  },
  {
    name: "géranium",
    category: "extérieur",
    id: "6uo",
    water: 1,
    light: 1,
    cover: monstera,
    price: 15,
  },
  {
    name: "basilique",
    category: "extérieur",
    id: "7ie",
    water: 1,
    light: 1,
    isSpecialOffer: true,
    cover: monstera,
    price: 15,
  },
  {
    name: "aloe",
    category: "plante grasse",
    id: "8fp",
    water: 1,
    light: 1,
    isSpecialOffer: true,
    cover: monstera,
    price: 15,
  },
  {
    name: "succulente",
    category: "plante grasse",
    id: "9vn",
    water: 1,
    light: 1,
    cover: monstera,
    price: 15,
  },
];
